name: Docker
run-name: Docker_run
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: apt-get docker.io
        run: |
          sudo apt-get remove containerd.io
          sudo apt install docker.io docker-compose -y

      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Build Docker
        run: docker build -t builder .
      - name: Run
        run: docker run --name test -t builder ls
      - name: Docker log
        run: docker cp test:/repo/log.txt ./log.txt

      - name: Upload_art
        uses: actions/upload-artifact@v4
        with:
          name: rep
          path: /home/runner/work/lab_work_8/lab_work_8/log.txt

